# blogs/_quarto.yml
project:
  type: website
  output-dir: articles
  render: 
    - "*.qmd"
    - "!_quarto.yml"
    
website:
  title: "Amiri Hayes' Blog"

format:
  html:
    theme: sandstone
    css: [styles.css]